### ISSUE TITLE
core dumy when run TUM

### ISSUE THREAD

**Issue by Wang-Minxin** [razayunus/ManhattanSLAM#7]
Hello, when I run TUM datasets, occurs core dump. In the core file, the error is 
#0  0x00007fc0c18df010 in g2o::EdgeSE3ProjectXYZOnlyPose::linearizeOplus() ()
    at /media/wmx/files/wmx/SLAM/ManhattanSLAM/Thirdparty/g2o/lib/libg2o.so
#1  0x00007fc0c2c74504 in g2o::BlockSolver<g2o::BlockSolverTraits<6, 3> >::buildSystem()
    () at /media/wmx/files/wmx/SLAM/ManhattanSLAM/lib/libManhattanSLAM.so
#2  0x00007fc0c1927228 in g2o::OptimizationAlgorithmLevenberg::solve(int, bool) ()
    at /media/wmx/files/wmx/SLAM/ManhattanSLAM/Thirdparty/g2o/lib/libg2o.so
#3  0x00007fc0c191f457 in g2o::SparseOptimizer::optimize(int, bool) ()
    at /media/wmx/files/wmx/SLAM/ManhattanSLAM/Thirdparty/g2o/lib/libg2o.so
#4  0x00007fc0c2c5fb0d in ORB_SLAM2::Optimizer::PoseOptimization(ORB_SLAM2::Frame*) ()
    at /media/wmx/files/wmx/SLAM/ManhattanSLAM/lib/libManhattanSLAM.so
#5  0x00007fc0c2c0bef5 in ORB_SLAM2::Tracking::TrackReferenceKeyFrame() ()
    at /media/wmx/files/wmx/SLAM/ManhattanSLAM/lib/libManhattanSLAM.so
#6  0x00007fc0c2c16339 in ORB_SLAM2::Tracking::Track() ()
    at /media/wmx/files/wmx/SLAM/ManhattanSLAM/lib/libManhattanSLAM.so
#7  0x00007fc0c2c19119 in ORB_SLAM2::Tracking::GrabImage(cv::Mat const&, cv::Mat const&, double const&) () at /media/wmx/files/wmx/SLAM/ManhattanSLAM/lib/libManhattanSLAM.so
#8  0x00007fc0c2bf2a03 in ORB_SLAM2::System::Track(cv::Mat const&, cv::Mat const&, double const&) () at /media/wmx/files/wmx/SLAM/ManhattanSLAM/lib/libManhattanSLAM.so
#9  0x0000557de2f6696c in main ()

I delete -march=native, but still occur this error. So, how can I solve this problem?

**Comment by Hbelief1998** [comment]
I have also encountered the same problem. Have you resolved it?

**Comment by sumture** [comment]
I have also encountered the same problem. Have you resolved it?
